board: None
name: Frankenstein Lunyee 3018 CNC
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
  segments: 12
spi:
  miso_pin: NO_PIN
  mosi_pin: NO_PIN
  sck_pin: NO_PIN
sdcard:
  cs_pin: NO_PIN
  card_detect_pin: NO_PIN
  frequency_hz: 8000000
kinematics: {}
axes:
  shared_stepper_disable_pin: gpio.47
  shared_stepper_reset_pin: NO_PIN
  homing_runs: 2
  x:
    steps_per_mm: 800
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 300
    soft_limits: true
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.36:low:pu
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: gpio.12
        direction_pin: gpio.14
        disable_pin: NO_PIN
    homing:
      cycle: 2
      positive_direction: false
      seek_mm_per_min: 500
      feed_mm_per_min: 20
  y:
    steps_per_mm: 800
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 180
    soft_limits: true
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.35:low:pu
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: gpio.8
        direction_pin: gpio.10:low
        disable_pin: NO_PIN
    homing:
      cycle: 2
      seek_mm_per_min: 500
      feed_mm_per_min: 20
      mpos_mm: 300
  z:
    steps_per_mm: 800
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 25
    max_travel_mm: 75
    soft_limits: true
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.48:low:pu
      hard_limits: true
      pulloff_mm: 1
      standard_stepper:
        step_pin: gpio.15
        direction_pin: gpio.17:low
        disable_pin: NO_PIN
    homing:
      cycle: 1
      positive_direction: true
      feed_mm_per_min: 20
      mpos_mm: 80
control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: gpio.37:low:pu
  cycle_start_pin: gpio.38:low:pu
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
  estop_pin: NO_PIN
probe:
  pin: gpio.2:low:pu
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
macros: {}
start:
  must_home: true
  deactivate_parking: false
  check_limits: true
parking:
  enable: false
  axis: Z
  target_mpos_mm: -5
  rate_mm_per_min: 800
  pullout_distance_mm: 5
  pullout_rate_mm_per_min: 250
user_outputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  analog0_hz: 5000
  analog1_hz: 5000
  analog2_hz: 5000
  analog3_hz: 5000
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN
user_inputs:
  analog0_pin: NO_PIN
  analog1_pin: NO_PIN
  analog2_pin: NO_PIN
  analog3_pin: NO_PIN
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN
  digital4_pin: NO_PIN
  digital5_pin: NO_PIN
  digital6_pin: NO_PIN
  digital7_pin: NO_PIN
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
PWM:
  output_pin: gpio.21
  pwm_hz: 78125
  disable_with_s0: true
  s0_with_disable: true
  spinup_ms: 2000
  spindown_ms: 2000
  speed_map: 0=0% 0=22% 10000=100%
